name: we_hack2025
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts: 
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf 
        - asset: assets/fonts/Inter_18pt-BlackItalic.ttf 
          style: italic
        - asset: assets/fonts/Inter_18pt-Bold.ttf 
          weight: 700
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf 
          style: italic
          weight: 700 
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf 
          weight: 800  
        - asset: assets/fonts/Inter_18pt-ExtraBoldItalic.ttf 
          style: italic
          weight: 800  
        - asset: assets/fonts/Inter_18pt-Italic.ttf 
          style: italic 
        - asset: assets/fonts/Inter_18pt-Light.ttf 
          weight: 300  
        - asset: assets/fonts/Inter_18pt-LightItalic.ttf 
          style: italic
          weight: 300   

        - asset: assets/fonts/Inter_24pt-Black.ttf 
        - asset: assets/fonts/Inter_24pt-BlackItalic.ttf 
          style: italic
        - asset: assets/fonts/Inter_24pt-Bold.ttf 
          weight: 700
        - asset: assets/fonts/Inter_24pt-BoldItalic.ttf 
          style: italic
          weight: 700 
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf 
          weight: 800  
        - asset: assets/fonts/Inter_24pt-ExtraBoldItalic.ttf 
          style: italic
          weight: 800  
        - asset: assets/fonts/Inter_24pt-Italic.ttf 
          style: italic 
        - asset: assets/fonts/Inter_24pt-Light.ttf 
          weight: 300  
        - asset: assets/fonts/Inter_24pt-LightItalic.ttf 
          style: italic
          weight: 300 

        - asset: assets/fonts/Inter_28pt-Black.ttf 
        - asset: assets/fonts/Inter_28pt-BlackItalic.ttf 
          style: italic
        - asset: assets/fonts/Inter_28pt-Bold.ttf 
          weight: 700
        - asset: assets/fonts/Inter_28pt-BoldItalic.ttf 
          style: italic
          weight: 700 
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf 
          weight: 800  
        - asset: assets/fonts/Inter_28pt-Italic.ttf 
          style: italic  
        - asset: assets/fonts/Inter_28pt-LightItalic.ttf 
          style: italic
          weight: 300 
       